config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :retrospectives
  resources :applications
  resources :interviews
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "main#index"

  resource :registration
  resource :session
  resource :password_reset
  resource :password

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/interviews_controller.rb
# frozen_string_literal: true

class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]

  # GET /interviews or /interviews.json
  def index
    @interviews = Interview.all
  end

  # GET /interviews/1 or /interviews/1.json
  def show
  end

  # GET /interviews/new
  def new
    @interview = Interview.new
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews or /interviews.json
  def create
    @interview = Interview.new(interview_params)

    respond_to do |format|
      if @interview.save
        format.html { redirect_to(interview_url(@interview), notice: "Interview was successfully created.") }
        format.json { render(:show, status: :created, location: @interview) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @interview.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /interviews/1 or /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to(interview_url(@interview), notice: "Interview was successfully updated.") }
        format.json { render(:show, status: :ok, location: @interview) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @interview.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /interviews/1 or /interviews/1.json
  def destroy
    @interview.destroy!

    respond_to do |format|
      format.html { redirect_to(interviews_url, notice: "Interview was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_interview
    @interview = Interview.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def interview_params
    params.require(:interview).permit(:type, :stage, :scheduled_at, :notes, :contact_id, :company_id)
  end
end

app/helpers/interviews_helper.rb
# frozen_string_literal: true

module InterviewsHelper
end

app/views/interviews/_form.html.erb
<%= form_with(model: interview, class: "contents") do |form| %>
  <% if interview.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
        <% interview.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :type %>
    <%= form.text_field :type, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :stage %>
    <%= form.text_field :stage, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :scheduled_at %>
    <%= form.datetime_field :scheduled_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.text_area :notes, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :contact_id %>
    <%= form.text_field :contact_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :company_id %>
    <%= form.text_field :company_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/interviews/_interview.html.erb
<div id="<%= dom_id interview %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Type:</strong>
    <%= interview.type %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Stage:</strong>
    <%= interview.stage %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Scheduled at:</strong>
    <%= interview.scheduled_at %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Notes:</strong>
    <%= interview.notes %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Contact:</strong>
    <%= interview.contact_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Company:</strong>
    <%= interview.company_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this interview", interview, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this interview", edit_interview_path(interview), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/interviews/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing interview</h1>

  <%= render "form", interview: @interview %>

  <%= link_to "Show this interview", @interview, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to interviews", interviews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/interviews/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Interviews</h1>
    <%= link_to "New interview", new_interview_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="interviews" class="min-w-full">
    <%= render @interviews %>
  </div>
</div>

app/views/interviews/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New interview</h1>

  <%= render "form", interview: @interview %>

  <%= link_to "Back to interviews", interviews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/interviews/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @interview %>

    <%= link_to "Edit this interview", edit_interview_path(@interview), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this interview", interview_path(@interview), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to interviews", interviews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>