config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :retrospectives
  resources :applications
  resources :interviews
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "main#index"

  resource :registration
  resource :session
  resource :password_reset
  resource :password

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flash.html.erb
<div class="<%= msg_type %> mb-5 border rounded text-sm p-4 flex items-center justify-between">
  <div class="flex items-center">
    <svg
        xmlns="http://www.w3.org/2000/svg"
        class="h-4 w-4 mr-2"
        viewBox="0 0 20 20"
        fill="currentColor"
        >
        <path
            fill-rule="evenodd"
            d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
            clip-rule="evenodd"
            />
    </svg>
    <p>
      <span class="font-bold">Info:</span>
      <%= message %>
    </p>
  </div>
  <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-6 w-6"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor" >
      <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M6 18L18 6M6 6l12 12"
          />
  </svg>
</div>

app/views/shared/_footer.html.erb
<footer class="bottom-0 mt-10 bg-cyan-900 text-white">
  <div class="container mx-auto px-8">
    <div class="w-full flex flex-col md:flex-row py-6">
      <div class="flex-1 mb-6">
        <%= render partial: 'shared/logo', locals: { text_color: "text-pink-600", line_color: "text-white" } %>
      </div>
      <div class="flex-1">
        <p class="uppercase text-white md:mb-6">Links</p>
        <ul class="list-reset mb-6">
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">FAQ</a>
          </li>
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">Help</a>
          </li>
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">Support</a>
          </li>
        </ul>
      </div>
      <div class="flex-1">
        <p class="uppercase text-white md:mb-6">Legal</p>
        <ul class="list-reset mb-6">
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">Terms</a>
          </li>
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">Privacy</a>
          </li>
        </ul>
      </div>
      <div class="flex-1">
        <p class="uppercase text-white md:mb-6">Social</p>
        <ul class="list-reset mb-6">
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">Facebook</a>
          </li>
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">Linkedin</a>
          </li>
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">Twitter</a>
          </li>
        </ul>
      </div>
      <div class="flex-1">
        <p class="uppercase text-white md:mb-6">Company</p>
        <ul class="list-reset mb-6">
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">Official Blog</a>
          </li>
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">About Us</a>
          </li>
          <li class="mt-2 inline-block mr-2 md:block md:mr-0">
            <a href="#" class="no-underline hover:underline text-gray-200 hover:text-pink-500">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_logo.html.erb
<%= link_to root_path, class: "#{text_color} toggleColour no-underline hover:no-underline font-bold text-2xl lg:text-4xl" do %>
  <svg class="h-8 fill-current inline" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512.005 512.005">
    <rect class="<%= line_color %>" x="16.539" y="425.626" width="479.767" height="50.502" transform="matrix(1,0,0,1,0,0)" />
    <path
        class="plane-take-off"
        d=" M 510.7 189.151 C 505.271 168.95 484.565 156.956 464.365 162.385 L 330.156 198.367 L 155.924 35.878 L 107.19 49.008 L 211.729 230.183 L 86.232 263.767 L 36.614 224.754 L 0 234.603 L 45.957 314.27 L 65.274 347.727 L 105.802 336.869 L 240.011 300.886 L 349.726 271.469 L 483.935 235.486 C 504.134 230.057 516.129 209.352 510.7 189.151 Z " />
  </svg>
  JOB SEARCH<span class="<%= line_color %> text-base animated-underline"><i>wtf</i></span>
<% end %>

app/views/shared/_navbar.html.erb
<header>
  <nav id="header" class="bg-cyan-900 fixed w-full z-10 top-0 text-white">
    <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 py-2">
      <div class="pl-4 flex items-center">
          <!--Icon from: http://www.potlabicons.com/ -->
          <%= render partial: 'shared/logo', locals: { text_color: "text-white", line_color: "text-pink-600" } %>
      </div>
      <div class="block lg:hidden pr-4">
        <button id="nav-toggle" class="flex items-center p-1 text-pink-800 hover:text-gray-900 focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out">
          <svg class="fill-current h-6 w-6" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <title>Menu</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
          </svg>
        </button>
      </div>
      <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden mt-2 lg:mt-0 bg-white lg:bg-transparent text-white p-4 lg:p-0 z-20" id="nav-content">
        <ul class="list-reset lg:flex justify-end flex-1 items-center">
          <% if user_signed_in? %>
            <li class="mr-3">
              <%= link_to "Edit Password", edit_password_path, class: "no-underline hover:text-gray-200 hover:text-underline" %>
            </li>
            <li class="mr-3">
              <%= button_to "Log Out", session_path, method: :delete, class: "btn-primary" %>
            </li>
          <% else %>
            <li class="mr-3">
              <%= link_to "Sign Up", new_registration_path, class: "no-underline hover:text-gray-200 hover:text-underline" %>
            </li>
            <li class="mr-3">
              <%= link_to "Sign In", new_session_path, class: "btn-primary" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_notices.html.erb
<div class="fixed md:w-96 sm:w-full inset-0 mt-4 px-4 py-6 sm:p-6 justify-self-end">
  <div id="notifications" class="flex flex-col items-end justify-center">
    <% flash.each do |type, data| %>
      <%= render NotificationComponent.new(type: type, data: data) %>
    <% end %>
  </div>
</div>