config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :retrospectives
  resources :applications
  resources :interviews
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "main#index"

  resource :registration
  resource :session
  resource :password_reset
  resource :password

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/retrospective.rb
# frozen_string_literal: true

class Retrospective < ApplicationRecord
  belongs_to :interview
  belongs_to :application
end

app/controllers/retrospectives_controller.rb
# frozen_string_literal: true

class RetrospectivesController < ApplicationController
  before_action :set_retrospective, only: [:show, :edit, :update, :destroy]

  # GET /retrospectives or /retrospectives.json
  def index
    @retrospectives = Retrospective.all
  end

  # GET /retrospectives/1 or /retrospectives/1.json
  def show
  end

  # GET /retrospectives/new
  def new
    @retrospective = Retrospective.new
  end

  # GET /retrospectives/1/edit
  def edit
  end

  # POST /retrospectives or /retrospectives.json
  def create
    @retrospective = Retrospective.new(retrospective_params)

    respond_to do |format|
      if @retrospective.save
        format.html do
          redirect_to(retrospective_url(@retrospective), notice: "Retrospective was successfully created.")
        end
        format.json { render(:show, status: :created, location: @retrospective) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @retrospective.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /retrospectives/1 or /retrospectives/1.json
  def update
    respond_to do |format|
      if @retrospective.update(retrospective_params)
        format.html do
          redirect_to(retrospective_url(@retrospective), notice: "Retrospective was successfully updated.")
        end
        format.json { render(:show, status: :ok, location: @retrospective) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @retrospective.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /retrospectives/1 or /retrospectives/1.json
  def destroy
    @retrospective.destroy!

    respond_to do |format|
      format.html { redirect_to(retrospectives_url, notice: "Retrospective was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_retrospective
    @retrospective = Retrospective.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def retrospective_params
    params.require(:retrospective).permit(:notes, :score, :interview_id, :application_id)
  end
end

app/helpers/retrospectives_helper.rb
# frozen_string_literal: true

module RetrospectivesHelper
end

app/views/retrospectives/_form.html.erb
<%= form_with(model: retrospective, class: "contents") do |form| %>
  <% if retrospective.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(retrospective.errors.count, "error") %> prohibited this retrospective from being saved:</h2>

      <ul>
        <% retrospective.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.text_area :notes, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :score %>
    <%= form.number_field :score, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interview_id %>
    <%= form.text_field :interview_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :application_id %>
    <%= form.text_field :application_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/retrospectives/_retrospective.html.erb
<div id="<%= dom_id retrospective %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Notes:</strong>
    <%= retrospective.notes %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Score:</strong>
    <%= retrospective.score %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Interview:</strong>
    <%= retrospective.interview_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Application:</strong>
    <%= retrospective.application_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this retrospective", retrospective, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this retrospective", edit_retrospective_path(retrospective), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/retrospectives/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing retrospective</h1>

  <%= render "form", retrospective: @retrospective %>

  <%= link_to "Show this retrospective", @retrospective, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to retrospectives", retrospectives_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/retrospectives/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Retrospectives</h1>
    <%= link_to "New retrospective", new_retrospective_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="retrospectives" class="min-w-full">
    <%= render @retrospectives %>
  </div>
</div>

app/views/retrospectives/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New retrospective</h1>

  <%= render "form", retrospective: @retrospective %>

  <%= link_to "Back to retrospectives", retrospectives_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/retrospectives/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @retrospective %>

    <%= link_to "Edit this retrospective", edit_retrospective_path(@retrospective), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this retrospective", retrospective_path(@retrospective), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to retrospectives", retrospectives_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>